### ISSUE TITLE
Test worksheet

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/sense-hat-minecraft-map#3]
@MissPhilbin @MarcScott @jrobinson-uk can one of you have a go?

**Comment by bennuttall** [comment]
@lauraclay @LornaLynch does one of you have time to run through the worksheet to make sure the steps work?

**Comment by LornaLynch** [comment]
I can have a go at it tomorrow if that's ok: I was up to my eyes in MagPi stuff today.

**Comment by bennuttall** [comment]
@LornaLynch did you finish working through it or do you have more to do? If you're done I'll close this and publish the resource

**Comment by LornaLynch** [comment]
Sorry: I should have closed this. I have finished.

**Comment by bennuttall** [comment]
Thanks!
