### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/sense-hat-minecraft-map#4]
@LornaLynch The images, template files and 'what next' are missing but can you copy edit the worksheet please?

**Comment by bennuttall** [comment]
Hi @LornaLynch I see a bunch of commits on this resource (thanks!). Have you finished copy editing, or is there more to do?

**Comment by LornaLynch** [comment]
It's pretty close but I need to give it another read through.

**Comment by bennuttall** [comment]
Ok thanks

**Comment by LornaLynch** [comment]
I think it's done now. I'll have another check when it's live on the website, but I'm going to close this issue for now.
