### ISSUE TITLE
Add cover image

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/sense-hat-minecraft-map#5]
Hey @samalderhyde can you create a cover image for this resource please?

The idea is you create a map of minecraft on the Sense HAT LED display - so you get an 8x8 grid of different coloured pixels showing sand, water, grass, etc.

I was thinking of a kid holding up a map (or a sense hat - or a map with a sense hat drawn on it) or something like that, walking around the minecraft world (a bit like the [mathematica](https://github.com/raspberrypilearning/getting-started-with-mathematica/blob/master/cover.png) one but with a grassy hill with sand and sea - blocky if that's not too awkward).

Sound ok?

**Comment by samalderhyde** [comment]
Sounds great
